# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/potentiostat-data-parser',
                'doc_host': 'https://bxw315-umd.github.io',
                'git_url': 'https://github.com/bxw315-umd/potentiostat-data-parser',
                'lib_path': 'potentiostat_data_parser'},
  'syms': {'potentiostat_data_parser.core': {'potentiostat_data_parser.core.foo': ('core.html#foo', 'potentiostat_data_parser/core.py')}}}
